language: php

php:
    - 7.4

env:
  global:
    - PHALCON_VERSION="v4.1.0"

git:
  depth: 1

matrix:
  fast_finish: true

cache:
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/assets

before_install:
  - |
    # php.ini configuration
    if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then
      find ~/.phpenv -name xdebug.ini -delete
    fi

install:
  - pecl install --force psr
  - .ci/install-phalcon.sh
  - travis_retry composer update --no-interaction --no-progress --no-ansi --no-suggest

script:
  - vendor/bin/codecept clean
  - vendor/bin/codecept build --quiet
  - vendor/bin/codecept run --coverage --coverage-xml

jobs:
  include:
    - stage: Test coverage
      if: branch = 4.x AND type = push
      php: 7.4
      script:
        - make coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.2
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

notifications:
  email:
    - dominic@headcrumbs.io
